# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: ''
baseurl: ''
title: 'Rylan Cole'
description: 'Personal website of UVic CSC student, Rylan Cole'
permalink: pretty
logo: "https://avatars2.githubusercontent.com/u/35235782?s=460&u=ac1060d4722c9a1a07e3a24f6e608dd0f21ef837&v=4"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Resume
  url: /resume/
- title: Blog
  url: /blog/

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
